FROM ubuntu:bionic@sha256:dca176c9663a7ba4c1f0e710986f5a25e672842963d95b960191e2d9f7185ebe

ENV TOKEN ${TOKEN}
ENV VERSION ${VERSION}

RUN apt-get -qq update && apt-get -qq install -y sudo curl wget git python3 python3-pip

RUN python3 -m pip install PyGithub

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

RUN git clone https://github.com/subalterngames/fast_image_encoder.git

WORKDIR ./fast_image_encoder/rs/fast_image_encoder

RUN cargo build --release

RUN cp target/release/libfast_image_encoder.so ../py/libfast_image_encoder.so

WORKDIR ../py

RUN python3 upload.py --token ${TOKEN} --version ${VERSION}